import { Inter } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'
import ToasterContext from "@/context/ToasterContext";
import { GlobalContextProvider } from "@/context/GlobalContext";
import Provider from "@/context/Auth";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <GlobalContextProvider>
            <ToasterContext />
            <NextUIProvider>
              {children}
            </NextUIProvider>
          </GlobalContextProvider>
        </Provider>

      </body>
    </html>
  );
}
